### ISSUE TITLE
Question: Help with Setting Up Demo Scene

### ISSUE THREAD

**Issue by androchentw** [SamuelAsherRivello/UnityDesignPatterns#1]
Hi Samuel,

First, I want to sincerely thank you for the amazing Unity tutorials! As a beginner, your content has been incredibly helpful, and I’ve learned a lot from your videos and articles.

I was able to successfully run the [unity-project-template](https://github.com/SamuelAsherRivello/unity-project-template) on Unity 6 with Windows 11. However, when working here with [unity-best-practices](https://github.com/SamuelAsherRivello/unity-best-practices), I couldn’t locate the demo scene. In Assets there was only 'Samples/' and 'TextMesh Pro/'. Could you kindly guide me on how to set it up?

Thanks again for all your hard work, I’m truly impressed by your passion and expertise. Looking forward to more of your fantastic series!

All the best

**Comment by SamuelAsherRivello** [comment]
Thanks for the kind words.

The https://github.com/SamuelAsherRivello/unity-template-project is to be used as the starting point for new projects. So it has scenes set up for that.

However, the https://github.com/SamuelAsherRivello/unity-best-practices is not meant as a starting point for a new project. Its meant for learning many topics. Each topic has its own scene. See the scenes within this folder for more info https://github.com/SamuelAsherRivello/unity-best-practices/tree/main/Unity/Assets/Samples/Topics. 

Enjoy!
